dataset:
    class_path: burn_emulator.datasets.IgnitionDataset
    init_args:
        ignitions_path: data/s1/outputs/1_legalmax/1_ignitions_locations.csv
        fuels_paths:
            -  data/s1/outputs/1_legalmax
        burn_paths:
            -  data/training_data_v8/legalmax/legalmax
        topo_path: data/topo
        stats_path: data/stats.yaml
        burn_times: [480]
        chip_size: 128
        jitter: null
        ignition_only: true
test_name: 1_legalmax
