dataset:
    class_path: burn_emulator.datasets.IgnitionDataset
    init_args:
        ignitions_path: null
        fuels_paths: null
        burn_paths: null
        topo_path: data/topo
        stats_path: data/stats.yaml
        burn_times: [480]
        chip_size: 128
        jitter: null

test_name: legalmax
num_iterations: 30
num_scenarios: 10
max_workers: 4
scenarios_path: data/PS_scenarios/s2/ignition_location_uncertainty