dataset:
    class_path: burn_emulator.datasets.IgnitionDataset
    init_args:
        ignitions_path: data/PS_scenarios/s2/outputs/5_baseline/5_ignitions_locations.csv
        fuels_paths:
            -  data/legalmax_baseline_FF_20260624
        burn_paths:
            -  data/training_data_v8/legalmax/baseline
        topo_path: data/topo
        stats_path: data/stats.yaml
        burn_times: [480]
        chip_size: 128
        jitter: null

test_name: 5_baseline
