dataset:
    class_path: burn_emulator.datasets.IgnitionDataset
    init_args:
        ignitions_path: data/PS_scenarios/s2/outputs/1_legalmax/1_ignitions_locations.csv
        fuels_paths:
            -  data/PS_scenarios/s2/outputs/1_legalmax
        burn_paths: null
        topo_path: data/topo
        stats_path: data/stats.yaml
        burn_times: [480]
        chip_size: 128
        jitter: null
activation: 
    class_path: torch.nn.Sigmoid
max_write_workers: 2
test_name: 1_legalmax
